name: Sync Upstream Repo

on:
  # schedule:
  #   - cron: '0 0 * * *' # Runs daily at midnight (UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the forked repository
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: feature/tbbeta-965

      # Step 2: Add the upstream repository
      - name: Add Upstream Repo
        run: |
          git remote add upstream https://github.com/OHIF/Viewers.git
          git fetch upstream release/3.9

      - name: create pull request
        run: gh pr create -B master -H release/3.9 --title 'OHIF updates' --body 'Review and merge or cancel'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # # Step 3: Merge changes from upstream
      # - name: Merge Upstream Changes
      #   run: |
      #     git checkout main
      #     git merge upstream/main --allow-unrelated-histories

      # # Step 4: Push changes to the fork
      # - name: Push Changes to Fork
      #   run: |
      #     git push origin main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
